config/routes.rb
Rails.application.routes.draw do
  
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'users#new'
  get 'choose'    => 'users#choose'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'newfield'  => 'fields#new'
  
  resources :users
  resources :users do
    member do
      get :following, :followers, :fields
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :fields 
  
  resources :events do
    match '/get_events' => 'events#get_events', as: :get_events, via:[:get,:post], on: :collection,  :defaults => { :format => 'json' }
  end
  

end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :team_player, presence: true
  validates :description, presence: true
  validates :user_id, presence: true
  has_many :events
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :logged_in_user, only:[:index]
  before_action :company_user?, only:[:new,:create,:update,:edit,:destroy]
#  before_action :correct_user,   only: [:edit,:update]
  
  def new
  	@field=Field.new
  	@field.user_id = current_user.id
  end

  def create
  	@field=Field.new(field_params)
  	if @field.save
  		flash[:info] = "Field create successfully."
  		redirect_to root_url
  	else
  		render 'new'
  	end
  end

  def edit
    @field=Field.find(params[:id])
  end

  def update
    @field=Field.find(params[:id])
    if @field.update_attributes(field_params)
      flash[:success] = "Field data updated"
      redirect_to @field
    else
      render 'edit'
    end
  end

  def show
    
    @field=Field.find(params[:id])
    
  end

  def destroy
    Field.find(params[:id]).destroy
    flash[:success] = "Field deleted"
    redirect_to fields_url
  end

  def index
    @fields = Field.paginate(page: params[:page])
  end

  private
  	def field_params
    	params.require(:field).permit(:name,:team_player,:description,
    								  :user_id)
    end

  	def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        redirect_to(root_url) 
        flash[:danger] = 'Access not authorized.'
      end
    end

  	def company_user
      redirect_to(root_url) unless company_user? || admin_user?
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_field.html.erb
<li>
  <%= gravatar_for field.user, size: 50 %>
  <%=link_to field.name, field %>
  <% if current_user?(field.user) || admin_user? %>
    | <%= link_to "delete", field, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/fields/edit.html.erb
<h1>Fields</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@field) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :team_player%>
      <%= f.number_field :team_player,min: 1, placeholder: "Cantidad de jugadores por equipo..." %>
	  <%= f.label :description%>
      <%= f.text_area :description, placeholder: "Describe las característica de ésta instalación..." %>
      <% if company_user? || admin_user? %>
      <%= f.hidden_field :user_id %>
      <%end%>
      <%= f.submit "Create my field game", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/fields/index.html.erb
<% provide(:title, 'All fields') %>
<h1>All fields</h1>
<%= will_paginate %>
<ul class="fields">

	<li>
	  <%= render @fields %>
	</li>
</ul>
<%= will_paginate %>

app/views/fields/new.html.erb
<h1>Fields</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@field) do |f| %>
    	<%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :team_player%>
      <%= f.number_field :team_player,min: 1, placeholder: "Cantidad de jugadores por equipo..." %>
	  <%= f.label :description%>
      <%= f.text_area :description, placeholder: "Describe las característica de ésta instalación..." %>
      <% if company_user? || admin_user? %>
      <%= f.hidden_field :user_id %>
      <%end%>
      <%= f.submit "Create my field game", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/fields/show.html.erb
<style type="text/css">
 

</style>



<% provide(:title, @field.name) %>

<div class="row" data-role="page" id="index">
  <aside class="col-md-4">
    <section>
      <h3>
        <%= gravatar_for @field.user %>
        <%= @field.user.name %>
      </h3>
    </section>
  </aside>
  <div class="col-md-6">
   	<h3> <%=@field.name%>  </h3> 
   	<% if current_user?(@field.user) || admin_user? %>  
   		<h3><span><%= link_to "Edit this field", edit_field_path %>-<%= link_to "Remove this field", field_path, method: "delete" %></span></h3>
   	<%end%>
   	<p>The field allows: <%= pluralize(@field.team_player,"player") %> per team. </p>
   	<p>Description: <%=@field.description%></p> 
  </div>
  <div class="col-md-2">
    <p align='left' > <%= link_to " Alquilar ahora ",'#', class: "btn btn-lg btn-primary" %></p>
    <p align='left' > <%= link_to "Consultar ahora",'#', class: "btn btn-lg btn-primary" %></p>
    
  </div>
  
  
</div>


<div class='calendar'></div>


<script type = "text/javascript">
  /*
    <% if admin_user? || company_user? %>
      var options = {
        header: {
          left: 'prev,next today',
          center: 'title',
          right: 'agendaWeek,agendaDay'
        },
        height: 500 ,
        slotMinutes: 30,
        dragOpacity: 0.5,
        eventColor: '#082E50',  
        eventOverlap:false,
        minTime: 7,
        allDaySlot:false,
        slotEventOverlap:false,
        firstDay:5,
        eventSources: [{
        url: '/events/get_events'
        }],
        timeFormat: "h:mm t{ - h:mm t}"
      };
      <% else %>
      var options = {
        header: {
          left: 'prev,next today',
          center: 'title',
          right: 'agendaWeek,agendaDay'
        },
        height: 500 ,
        slotMinutes: 30,
        dragOpacity: 0.5,
        eventColor: '#218A04',
        eventOverlap:false,
        minTime: 7,
        allDaySlot:false,
        nowIndicator:true,
        slotEventOverlap:false,
        editable:false,
        firstDay:5,
        selectable:false,
         eventClick:  function(event, jsEvent, view) {
          
          }
      };     
    
    <% end %>
    $('.calendar').fullCalendar($.extend(full_calendar_options,options));
*/
$(document).ready(function() {


    $('.calendar').fullCalendar({
        // put your options and callbacks here
         theme: false,
         defaultView:'agendaWeek',
         header: {
          left: 'prev,next today',
          center: 'title',
          right: 'agendaWeek,agendaDay'
        },
        events: {
          url:'/events/get_events',
          type: 'POST',
          data: {
            field: <%=@field.id%>
          },
          error: function() {
              alert('there was an error while fetching events!');
          }
        },
        allDayText:'Estado',
        minTime:'06:00:00', //Configuration data
        maxTime:'23:59:59',
        timeFormat:'H(:mm)',
        columnFormat:'dddd M/D',
        firstDay:<%= Time.at(Time.now).wday%>, //today
        selectable: true
      });
    });
  </script>



 