config/routes.rb
Rails.application.routes.draw do
  
  root               'static_pages#home'
  get 'help'      => 'static_pages#help'
  get 'about'     => 'static_pages#about'
  get 'contact'   => 'static_pages#contact'
  get 'signup'    => 'users#new'
  get 'choose'    => 'users#choose'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'newfield'  => 'fields#new'
  
  resources :users
  resources :users do
    member do
      get :following, :followers, :fields
    end
  end
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :fields 
  
  resources :events do
    match '/get_events' => 'events#get_events', as: :get_events, via:[:get,:post], on: :collection,  :defaults => { :format => 'json' }
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by <a href="http://www.railstutorial.org/">Smarteam | Updating your future</a>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",  about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CORNER APP", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Inicio", root_path %></li>
        <li><%= link_to "Ayuda", help_path %></li>
        <% if logged_in? %>
          <%if admin_user?%>
            <li><%= link_to "Usuarios", users_path %></li>
            <li><%= link_to "Canchas", fields_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= name_current_user %> - ADMIN<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Perfil", current_user %></li>
                  <li><%= link_to "Configuración", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
          <%else%>
            <% if company_user? %>
              <li><%= link_to "Usuarios", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= name_current_user %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Perfil", current_user %></li>
                  <li><%= link_to "Configuración", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <%else # is person user %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <%= name_current_user %> <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Perfil", current_user %></li>
                    <li><%= link_to "Configuración", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Log out", logout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
            <%end%>
          <%end%>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>